INSERT INTO post(id, title, photo, /*ingredient,*/ content, author) VALUES
    (1, 'Chorizo & mozzarella gnocchi bake',
        'gnocchi-1d16725.png',
--         1,
        'Content 1',
        'First author'),
    (2, 'Easy classic lasagne',
        'classic-lasange-4a66137.png',
--         2,
        'Content 2',
        'Second author'),
    (3, 'Easy carrot cake',
        'carrot-cake-f1b3d0c.png',
--         3,
        'Content 3',
        'Third author')
;

-- INSERT INTO ingredient(id, post_id, value) VALUES
--     (1, 1, '1 tbsp olive oil'),
--     (2, 1, '1 onion , finely chopped'),
--     (3, 1, '2 garlic cloves , crushed'),
--     (4, 1, '120g chorizo , diced'),
--     (5, 1, '2 x 400g cans chopped tomatoes'),
--     (6, 1, '1 tsp caster sugar'),
--     (7, 1, '600g fresh gnocchi'),
--     (8, 1, '125g mozzarella ball, cut into chunks'),
--     (9, 1, 'small bunch of basil , torn'),
--     (10, 1, 'green salad , to serve'),
--
--     (11, 2, '1 tbsp olive oil'),
--     (12, 2, '2 rashers smoked streaky bacon'),
--     (13, 2, '1 onion , finely chopped'),
--     (14, 2, '1 celery stick, finely chopped'),
--     (15, 2, '1 medium carrot , grated'),
--     (16, 2, '2 garlic cloves , finely chopped'),
--     (17, 2, '500g beef mince'),
--     (18, 2, '1 tbsp tomato purée'),
--     (19, 2, '2 x 400g cans chopped tomatoes'),
--     (20, 2, '1 tbsp clear honey'),
--     (21, 2, '500g pack fresh egg lasagne sheets'),
--     (22, 2, '400ml crème fraîche'),
--     (23, 2, '125g ball mozzarella , roughly torn'),
--     (24, 2, '50g freshly grated parmesan'),
--     (25, 2, 'large handful basil leaves , torn (optional)'),
--
--     (26, 3, '230ml vegetable oil, plus extra for the tin'),
--     (27, 3, '100g natural yogurt'),
--     (28, 3, '4 large eggs'),
--     (29, 3, '1½ tsp vanilla extract'),
--     (30, 3, '½ orange, zested'),
--     (31, 3, '265g self-raising flour'),
--     (32, 3, '335g light muscovado sugar'),
--     (33, 3, '2½ tsp ground cinnamon'),
--     (34, 3, '¼ fresh nutmeg, finely grated'),
--     (35, 3, '265g carrots (about 3), grated'),
--     (36, 3, '100g sultanas or raisins'),
--     (37, 3, '100g walnuts or pecans, roughly chopped (optional)'),
--     (38, 3, '100g slightly salted butter, softened'),
--     (39, 3, '300g icing sugar'),
--     (40, 3, '100g soft cheese')
-- ;